include:
  - template: AWS/Deploy-ECS.gitlab-ci.yml

variables:
  CI_AWS_ECS_CLUSTER: default
  CI_AWS_ECS_SERVICE: predictions-bot-service
  CI_AWS_ECS_TASK_DEFINITION: predictions-bot
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

testing:
  only:
    - merge_requests
  image: python:3.9-buster
  stage: test
  variables:
    API_KEY: NOTAREALTOKEN
    TESTING: "TRUE"
    PYTHONUNBUFFERED: 1
    LOGLEVEL: DEBUG
    GITLAB_API: $GITLAB_API
    TOKEN: $TOKEN
    AWS_DBPASS: $AWS_DBPASS
  cache:
    paths:
      - .cache/pip
      - venv/
    key: one-key-to-rule-them-all
  script:
    - python3 -m venv venv
    - source ./venv/bin/activate
    - python -m pip install -r requirements.txt
    - pytest -srpfE --cov-report term-missing --cov='./src'
