workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^master/'

job:
  image: python:3.9-buster
  script:
    - python3 -m venv venv
    - source ./venv/bin/activate
    - python -m pip install -r requirements.txt
    - pytest -srpfE --cov-report term-missing --cov='.'

include:
  - template: AWS/Deploy-ECS.gitlab-ci.yml

variables:
  CI_AWS_ECS_CLUSTER: default
  CI_AWS_ECS_SERVICE: predictions-bot-service
  CI_AWS_ECS_TASK_DEFINITION: predictions-bot